name: Build aarch64 wheels

on:
 push:
  tags:
   - 'v*'
 workflow_dispatch:
  inputs:
   release_version:
    description: release version tag for the release

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_LINUX: aarch64
          CIBW_BUILD: cp39-manylinux_aarch64 cp310-manylinux_aarch64
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  github-release:
    name: Release
    runs-on: ubuntu-latest
    if: "github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')"
    needs: [ build_wheels ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_version || github.ref }}
          files: '*.whl'
